### ISSUE TITLE
[BUG] Using wait in CI

### ISSUE THREAD

**Issue by SteelAlloy** [denosaurs/wait#4]
When used in a CI env, `wait` throws an error.
```
"Error: Inappropriate ioctl for device (os error 25)\n    at Object.jsonOpSync (core.js:247:13)\n    at Object.consoleSize (deno:cli/rt/40_tty.js:7:17)\n    at Spinner.updateLines (mod.ts:201:26)\n    at Spinner.set text (mod.ts:128:10)\n    at new Spinner (mod.ts:83:14)\n    at wait (mod.ts:48:10)\n    at Function.info (log.ts:182:12)\n    at checkUp (publish.ts:156:26)\n    at Command.publishCommand [as fn] (publish.ts:272:14)\n    at async Command.execute (command.ts:796:9)"
```
https://github.com/nestdotland/eggs/pull/79/checks?check_run_id=1138695456#step:6:797

**Comment by eliassjogreen** [comment]
This is most likely an error with deno itself considering it seems to originate in `cli/rt/40_tty.js:7:17`.

**Comment by notfilippo** [comment]
Agree with @eliassjogreen
